name: flutter_bluetooth
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #State Management
  get: 4.3.8

  #Bluetooth
  flutter_reactive_ble: ^5.0.2
  flutter_bluetooth_serial: ^0.4.0

  #Other Packages
  cupertino_icons: ^1.0.2
  permission_handler: ^8.2.2
  double_back_to_close: ^2.0.0
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
